name: Post-merge

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    uses: kyhule/polyworld-workflows/.github/workflows/post-merge.yml@95291f10a9811bfbb87098cf3a3765a2ac95919f
    secrets: inherit
    with:
      android-archive-app-outputs: true
      android-archive-app-reports: true
      publish-artifacts: false
      publish-release: false
