name: Post-merge

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    uses: kyhule/polyworld-workflows/.github/workflows/post-merge.yml@9b3a29e80ac7e384885fdfaeee2d6979e47f962f
    secrets: inherit
    with:
      android-archive-app-outputs: true
      android-archive-app-reports: true
      publish-artifacts: false
      publish-release: false
