name: Post-merge

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    uses: kyhule/polyworld-workflows/.github/workflows/post-merge.yml@a26f05dbaa65b38aef88fd576709fdce64059d07
    secrets: inherit
    with:
      android-archive-app-outputs: true
      android-archive-app-reports: true
      publish-artifacts: false
      publish-release: false
