name: Post-merge

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    uses: kyhule/polyworld-workflows/.github/workflows/post-merge.yml@f0a535faadb2aafdd961219125457f01ad2964f1
    secrets: inherit
    with:
      android-archive-app-outputs: true
      android-archive-app-reports: true
      publish-artifacts: false
      publish-release: false
