name: Pre-merge

on:
  pull_request:
    paths-ignore:
      - '*.md'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false

jobs:
  build:
    uses: kyhule/polyworld-workflows/.github/workflows/pre-merge.yml@a26f05dbaa65b38aef88fd576709fdce64059d07
    secrets: inherit
